language: python
python:
  - "3.8"
  - "3.7"
  - "3.6"
  - "3.5"
  - "3.4"
  - "2.7"

install:
  - python setup.py sdist bdist_wheel
  - pip install dist/*.whl
  - pip install twine flake8 pytest

script:
  - twine check dist/*

  # flake8 is a static analysis tool based on:
  # - pyflakes: static analysis (syntax errors, unused variables, etc)
  # - pycodestyle: style checks
  # - mccabe: complexity analysis
  - flake8 --exclude 'pyqtconsole/qt,build'
  - flake8 --exclude '' pyqtconsole/qt --ignore F401,F403,F811
  - pytest

jobs:
  include:
    - stage: deploy
      name: Upload release to PyPI
      if: tag is present
      script: twine upload dist/*
      env:
        - TWINE_USERNAME=pyqtconsole
        # TWINE_PASSWORD:
        - secure: "CZyGAfm/N0F4Px+d6F4MPUoWc7PILkTrB8Jc/IwmULCPf74bvvq7bREjH+eicoppuGR9sD1Yj1tlqPQcpAPbkH7G/JuKXgUHZd8QMQmQunrYsdNc3neKfi4nNMcGH3e+diyz4hKNyYYi+IwxgD42Pa2DPI85D53gz4QMpIgVwBamSKj+fQAlnaF8PXaYtH3lTkdM9Adwp13PLD1edaDvRklfsDcsCahehi7IOOjUQzPRDHOgHjKq5JPVP5+K7rGgZwB244xsuIvB0d6i8zRNihm/6uVpxblB6DLsDfPMOFBY4Va5lPS4MSZ4JZoyUuIfo2Gp9LjyzTN8PXQNtRqtUQ957nyZf/hS7KIqEEqPvnDBUhOF6mlB/iOqSVe33fLRCiuvzI5Gsgg2zhKG5l/gTwb1U9J5an2YFWX6GXuyai24fl8kfNWSAJH4ppQy9cZhgMUYE3yYivXK4IQA+y5AIyDn9Ptm/chwCt20IJN92PPFf/mhEKBmJ7cBA7skyrAVX9a8HdLEvs03Yg5eKSkelD7mHXt7tMV2wGG8cAJbYoQFQnQgPppOQNZ+fyj07Bmfn5XDYr9ayCcrAOxvHJ54mUz5xl8e+z1g77jttdBU6Z5FfT+pupbY+m/hDawWU3iZLbD379lsCg0sy26D1oHDR+z8XqBXWj+87yXiFJWfSfo="
